### ISSUE TITLE
Bug in 5.1.0: postContactsTransactionalData is broken

### ISSUE THREAD

**Issue by technik-vitafy** [dotmailer/dotmailer-magento-extension#8] opened 2015-12-02 19:30 UTC
Since the method uses the undefined order class attribute connector_id  the REST API call always fails since ContactIdentifier is mandatory. 
Following notice is generated:

Notice: Undefined property: Dotdigitalgroup_Email_Model_Connector_Order::$connector_id in /opt/magento/.modman/dotmailer-magento-extension/code/Dotdigitalgroup/Email/Model/Apiconnector/Client.php on line 670

This could be fixed by following patch. Please verify this - thanks!
![screen shot 2015-12-02 at 18 53 38](https://cloud.githubusercontent.com/assets/13380473/11541581/3fafaefe-9933-11e5-952d-7781c124ccd5.png)

**Comment by equinoxmatt** [comment] 2016-02-02 17:34
I can confirm we also have this issue. Due to be fixed?

**Comment by cdiacon** [comment] 2016-02-02 21:08
@equinoxmatt yes this should be fixed in 5.2.0

**Closed by cdiacon** 2016-02-02 21:08 UTC

**Comment by equinoxmatt** [comment] 2016-02-03 09:21
Not sure how fixed this is?  Upgraded to 5.2.0 last night, and getting a slightly different error:

`2016-02-02T18:05:03+00:00 ERR (3): Notice: Undefined property: Dotdigitalgroup_Email_Model_Connector_Product::$email  in /home/d365main/public_html/supplies/app/code/community/Dotdigitalgroup/Email/Model/Apiconnector/Client.php on line 670`

**Comment by cdiacon** [comment] 2016-02-03 09:29
@equinoxmatt this issue fixed the postContactsTransactionalDataImport() 

this is the notice for postContactsTransactionalData()
